#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/ConsenSys/mythril
   """
from sys import exit
import mythril.interfaces.cli
import time

if __name__ == "__main__":
    # mythril.interfaces.cli.main()
    # exit()

    seconds_start = time.time()
    mythril.interfaces.cli.main()
    # exit()
    seconds_end = time.time()
    print(f'#@time')
    print(f'time used:{seconds_end-seconds_start}')

